---

- name: Installing filebeat from apt repository
  apt: 
    name: filebeat
    state: present
    update_cache: yes

- name: Copying config file 
  template: 
    src: filebeat.j2
    dest: /etc/filebeat/filebeat.yml

- name: Reloading systemd daemon
  systemd: 
    daemon_reload: yes

- name: Enabling filebeat.service
  systemd:
    name: filebeat.service
    enabled: yes

- name: Start filebeat.service
  systemd: 
    name: filebeat.service
    state: restarted
  become: true
