---

- name: Installing kibana from apt repository
  apt: 
    name: kibana
    state: present
    update_cache: yes

- name: Copying config file 
  template: 
    src: kibana.j2
    dest: /etc/kibana/kibana.yml

- name: Reloading systemd daemon
  systemd: 
    daemon_reload: yes

- name: Enabling kibana.service
  systemd:
    name: kibana.service
    enabled: yes

- name: Start kibana.service
  systemd: 
    name: kibana.service
    state: restarted
  become: true
